# Generated by Django 2.0 on 2018-03-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotonLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_boton', models.CharField(max_length=100)),
                ('nombre_habitacion', models.CharField(max_length=100)),
                ('coordenada_x_position', models.IntegerField()),
                ('coordenada_y_position', models.IntegerField()),
                ('coordenada_z_position', models.IntegerField()),
                ('coordenada_x_rotation', models.IntegerField()),
                ('coordenada_y_rotation', models.IntegerField()),
                ('coordenada_z_rotation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_casa', models.CharField(max_length=100)),
                ('numero_habitaciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_casa', models.CharField(max_length=100)),
                ('nombre_habitacion', models.CharField(max_length=100)),
                ('nombre_boton', models.CharField(max_length=100)),
                ('link_habitacion', models.CharField(max_length=100)),
                ('imagen_habitacion', models.FileField(upload_to='')),
            ],
        ),
    ]
