# Generated by Django 2.0.2 on 2018-03-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesHabitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_habitacion', models.CharField(max_length=100)),
                ('imagen_habitacion', models.FileField(upload_to='')),
                ('nombre_habitacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='imagen_habitacion',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='link_habitacion',
        ),
    ]
