# Generated by Django 2.0.2 on 2018-03-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVR', '0002_auto_20180322_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botonlink',
            name='coordenada_x_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='botonlink',
            name='coordenada_x_rotation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='botonlink',
            name='coordenada_y_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='botonlink',
            name='coordenada_y_rotation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='botonlink',
            name='coordenada_z_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='botonlink',
            name='coordenada_z_rotation',
            field=models.FloatField(),
        ),
    ]
