# Generated by Django 2.0.2 on 2018-03-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVR', '0003_auto_20180322_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageneshabitaciones',
            name='link_habitacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
