# Generated by Django 2.0.2 on 2018-03-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appVR', '0004_auto_20180322_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habitacion',
        ),
        migrations.DeleteModel(
            name='ImagenesHabitaciones',
        ),
    ]
